export const SIGNUP      = 'signup'
export const SIGNIN      = 'signin'
export const SIGNOUT     = 'signout' 
export const AUTO_SIGNIN = 'auto_signin'
export const CHANGE_PASSWORD  = 'change_password'
export const RESET_AUTH_ERROR = 'reset_auth_error'
export const SET_AUTH_ERROR    = 'set_error'
export const CLEAR_AUTH_ERROR  = 'clear_error'
export const SET_USER     = 'set_user'
export const CLEAR_USER   = 'clear_user'

export const CREATE_ITEM = 'create_item'
export const FETCH_ITEMS = 'fetch_items'
export const SET_ITEMS = 'set_items'
export const ADD_ITEM = 'add_item'

export const SET_LOADING_STATE = 'set_loading_state'